import assert from "node:assert/strict";
import test from "node:test";
import { mkdtemp, mkdir, rm, writeFile, readdir } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { ProState } from "../../src/project-reader/pro-state.js";
import { ProSession } from "../../src/project-reader/pro.js";

test("state lease rejects duplicate processes; exact scope restores patch and apply receipts", async t => {
  const root = await mkdtemp(join(tmpdir(), "pro-state-"));
  t.after(() => rm(root, { recursive: true, force: true }));
  const project = join(root, "project"); await mkdir(project);
  const file = join(root, "state.json"), scope = { project };
  const first = await ProState.acquire(file, scope, [project]);
  await assert.rejects(ProState.acquire(file, scope, [project]), /in use/);
  await first.begin("submit_controlled_patch", null);
  await first.finish("submit_controlled_patch", {}, { task_id: "patch-1" });
  await first.begin("apply_controlled_patch", "patch-1");
  await first.finish("apply_controlled_patch", { patch_task_id: "patch-1" }, { applied: true, changed_paths: ["README.md"] });
  await first.close();
  await assert.rejects(ProState.acquire(file, { changed: true }, [project]), /configuration changed/);
  const second = await ProState.acquire(file, scope, [project]);
  assert.deepEqual(second.patches, ["patch-1"]);
  assert.deepEqual(second.receipts["patch-1"], { applied: true, changed_paths: ["README.md"] });
  assert.equal(second.inFlight, null);
  await second.close();
  await assert.rejects(ProState.acquire(join(project, "state.json"), scope, [project]), /outside/);
});

test("lost mutation intent survives restart and blocks duplicate effects", async t => {
  const root = await mkdtemp(join(tmpdir(), "pro-intent-"));
  t.after(() => rm(root, { recursive: true, force: true }));
  const project = join(root, "project"); await mkdir(project);
  const config = { version: 1, reader: { version: 1, projects: [{ id: "demo", name: "Demo", root: project, share: ["."] }] }, bridge: { entry: join(root, "bridge.js"), workspaces_config: join(root, "ws.json"), workspace_ids: ["demo"], allow_workers: false } };
  const file = join(root, "state.json");
  const first = await ProState.acquire(file, config, [project]);
  let calls = 0;
  const broken = await ProSession.create(config, async () => { calls++; throw new Error("connection lost"); }, first);
  const input = { workspace_id: "demo", base_head: "a".repeat(40), diff: "fixture" };
  await assert.rejects(broken.call("continuity_patch_submit", input), /outcome may be unknown/);
  await first.close();
  const second = await ProState.acquire(file, config, [project]);
  const restored = await ProSession.create(config, async () => { calls++; return {}; }, second);
  await assert.rejects(restored.call("continuity_patch_submit", input), /response was lost/);
  assert.equal(calls, 1);
  assert.equal(second.inFlight?.operation, "submit_controlled_patch");
  await second.close();
});

test("worker result ownership survives restart but live control authority does not", async t => {
  const root = await mkdtemp(join(tmpdir(), "pro-worker-state-"));
  t.after(() => rm(root, { recursive: true, force: true }));
  const project = join(root, "project"); await mkdir(project);
  const config = { version: 1, reader: { version: 1, projects: [{ id: "demo", name: "Demo", root: project, share: ["."] }] }, bridge: { entry: join(root, "bridge.js"), workspaces_config: join(root, "ws.json"), workspace_ids: ["demo"], allow_workers: true } };
  const path = join(root, "state.json"), first = await ProState.acquire(path, config, [project]);
  const session = await ProSession.create(config, async name => name === "task_result" ? { ready: true, state: "waiting_for_supervisor_review", executor: "dsh", review_output: "actual retained fixture" } : { task_id: "worker-owned" }, first);
  await session.call("continuity_worker_start", { workspace_id: "demo", kind: "analysis", instruction: "synthetic boundary test" });
  await session.call("continuity_task_result", { task_id: "worker-owned" });
  await first.close();
  const second = await ProState.acquire(path, config, [project]);
  const restored = await ProSession.create(config, async () => { throw new Error("Prior Bridge process has no task memory"); }, second);
  assert.deepEqual(second.workers, ["worker-owned"]);
  assert.equal((await restored.call("continuity_task_result", { task_id: "worker-owned" }) as { ready: boolean }).ready, true);
  assert.equal((await restored.call("continuity_task_result", { task_id: "worker-owned" }) as { review_output: string }).review_output, "actual retained fixture");
  assert.equal((await restored.call("continuity_task_result", { task_id: "worker-owned" }) as { historical: boolean }).historical, true);
  await assert.rejects(restored.call("continuity_worker_control", { task_id: "worker-owned", action: "continue" }), /Only DSH tasks started/);
  await second.close();
});

test("explicit idle lease recovery archives dead owners but refuses live owners and unknown effects", async t => {
  const { spawn } = await import("node:child_process");
  const child = spawn(process.execPath, ["-e", ""], { windowsHide: true, stdio: "ignore" });
  const deadPid = child.pid;
  await new Promise<void>((resolve, reject) => { child.once("exit", () => resolve()); child.once("error", reject); });
  assert.ok(deadPid);
  const root = await mkdtemp(join(tmpdir(), "pro-idle-recovery-"));
  t.after(() => rm(root, { recursive: true, force: true }));
  const project = join(root, "project"); await mkdir(project);
  const file = join(root, "state.json"), lock = file + ".lock", scope = { project };
  const live = await ProState.acquire(file, scope, [project]);
  await assert.rejects(ProState.acquire(file, scope, [project], { recoverIdleOwner: true }), /still alive/);
  await live.close();
  await mkdir(lock); await writeFile(join(lock, "owner.json"), JSON.stringify({ pid: deadPid }));
  const recovered = await ProState.acquire(file, scope, [project], { recoverIdleOwner: true });
  assert.ok((await readdir(root)).some(name => name.startsWith("state.json.lock.stale.")));
  await recovered.begin("apply_controlled_patch", "unknown-patch");
  await recovered.close();
  await mkdir(lock); await writeFile(join(lock, "owner.json"), JSON.stringify({ pid: deadPid }));
  await assert.rejects(ProState.acquire(file, scope, [project], { recoverIdleOwner: true }), /Retained effects/);
  const workerFile = join(root, "worker-state.json"), workerLock = workerFile + ".lock";
  const workerState = await ProState.acquire(workerFile, scope, [project]);
  await workerState.finish("run_task", {}, { task_id: "settled-worker" });
  await workerState.observeWorker("settled-worker", { executor: "dsh", ready: true, state: "completed", output: "read-only output" });
  await workerState.close();
  await mkdir(workerLock); await writeFile(join(workerLock, "owner.json"), JSON.stringify({ pid: deadPid }));
  const settled = await ProState.acquire(workerFile, scope, [project], { recoverIdleOwner: true });
  assert.equal(settled.workerResult("settled-worker")?.historical, true);
  await settled.begin("control_task", "settled-worker");
  assert.equal(settled.workerResult("settled-worker"), undefined);
  await settled.close();
  await mkdir(workerLock); await writeFile(join(workerLock, "owner.json"), JSON.stringify({ pid: deadPid }));
  await assert.rejects(ProState.acquire(workerFile, scope, [project], { recoverIdleOwner: true }), /Retained effects/);
});
